// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-4QKM7nueuhOwGlgosq333qOLf40LQ8',
    appId: '1:126188958022:web:ee136ee12eab9be388b547',
    messagingSenderId: '126188958022',
    projectId: 'koncept-8ad53',
    authDomain: 'koncept-8ad53.firebaseapp.com',
    storageBucket: 'koncept-8ad53.firebasestorage.app',
    measurementId: 'G-9Y6G6JE6NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQuySUr6aFFbzGf7YDd6shgrWwPicnesI',
    appId: '1:126188958022:android:03030bb19d1e373d88b547',
    messagingSenderId: '126188958022',
    projectId: 'koncept-8ad53',
    storageBucket: 'koncept-8ad53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS6zeuXrtF40K62ENoa9EbnMYM9gmxjYY',
    appId: '1:126188958022:ios:1245dea0b9d7263388b547',
    messagingSenderId: '126188958022',
    projectId: 'koncept-8ad53',
    storageBucket: 'koncept-8ad53.firebasestorage.app',
    iosClientId: '126188958022-qmnd2tj0i0df86q1ih6iuqkhhhb60cvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.konceptInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ-4QKM7nueuhOwGlgosq333qOLf40LQ8',
    appId: '1:126188958022:web:f12ab18847e2514888b547',
    messagingSenderId: '126188958022',
    projectId: 'koncept-8ad53',
    authDomain: 'koncept-8ad53.firebaseapp.com',
    storageBucket: 'koncept-8ad53.firebasestorage.app',
    measurementId: 'G-28QMQFWG4G',
  );
}
